@startuml
'https://plantuml.com/class-diagram

class Participante{
    -String nombre
    -String apellido
    -int edad
    -String telefono
    -String correo
    -String nacionalidad
    -boolean certificadoMedico
    -boolean aceptoTerminos
    +Participante(String nombre, String apellido)
    +Participante(String nombre, int edad, String telefono)
    +Participante(String nombre, String apellido, int edad, String telefono, String correo, String nacionalidad, boolean certificadoMedico, boolean aceptoTerminos)
    +String getNombre()
    +void setNombre(String nombre)
    +String getApellido()
    +void setApellido(String apellido)
    +int getEdad()
    +void setEdad(int edad)
    +String getTelefono()
    +void setTelefono(String telefono)
    +String getCorreo()
    +void setCorreo(String correo)
    +String getNacionalidad()
    +void setNacionalidad(String nacionalidad)
    +boolean getCertificadoMedico()
    +void setCertificadoMedico(boolean certificadoMedico)
    +boolean getAceptoTerminos()
    +void setAceptoTerminos()

}

@enduml